# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent

service:
  name: edgefs
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 15
  successThreshold: 3
  timeoutSeconds: 3
readinessProbe:
  periodSeconds: 15
  successThreshold: 3
  timeoutSeconds: 3
terminationGracePeriodSeconds: 10
